name: yes24_crawler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          version: 'stable'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          # ChromeDriver 버전을 Chrome의 버전에 맞춰 지정합니다.
          chromedriver-version: '116.0.5845.96'  # 올바른 버전으로 교체 필요

      - name: Run main.py
        run: |
          python main.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
