name: yes24_crawler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 114.0.5735.90  # Chrome 버전에 맞는 ChromeDriver 버전 지정

      - name: Run main.py
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          export DISPLAY=:99
          chromedriver --version
          google-chrome --version
          python main.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

