name: seochoroom_crawler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 * * * *" # 매월1일작동(0 0 1 * *) / 참고 : 매일마다 작동 (0 * * * *)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 114.0.5735.90 # Chrome 버전에 맞는 ChromeDriver 버전 지정

      - name: Run roomservice.py
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          export DISPLAY=:99
          chromedriver --version
          google-chrome --version
          python roomservice.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
